POST http://localhost:8080/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET http://localhost:8080/comments HTTP/1.1

###

GET http://localhost:8080/comments/1 HTTP/1.1

###

GET http://localhost:8080/comments?name=My%20name

###

POST http://localhost:8080/subnets

{
  "name": "192.168.0.0/24",
  "gateway": "192.168.0.1"
}